**Create a NumPy array with values from 1 to 10, then compute the square root and the square of all the elements.**

In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(array) #To compute square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [5]:
np.square(array) #To compute Square

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])